USE DIVERSOS_TESTES;
GO

CREATE SCHEMA TOPAZ;
GO

CREATE TABLE TOPAZ.TB_FAIXA 
(
	ID						UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	TITULO					NVARCHAR(50) NOT NULL,
	DURACAO					DECIMAL NOT NULL,
	ARTISTA					NVARCHAR(50) NOT NULL,
	DATA_CADASTRO			DATETIME NOT NULL DEFAULT GETDATE()
);

INSERT INTO TOPAZ.TB_FAIXA (ID, TITULO, DURACAO, ARTISTA) VALUES (NEWID(), 'Curtains Up', 3.5, 'EMINEM')
INSERT INTO TOPAZ.TB_FAIXA (ID, TITULO, DURACAO, ARTISTA) VALUES (NEWID(), 'Cleaning Ou My Closet', 2.8, 'EMINEM')
INSERT INTO TOPAZ.TB_FAIXA (ID, TITULO, DURACAO, ARTISTA) VALUES (NEWID(), 'Say Goodbye Hollywood', 4.0, 'EMINEM')

CREATE TABLE TOPAZ.TB_GENERO 
(
	ID						UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	NOME					NVARCHAR(50) NOT NULL,
	DATA_CADASTRO			DATETIME NOT NULL DEFAULT GETDATE()
);

INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'ROCK');
INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'SAMBA');
INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'SERTANEJO');
INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'MPB');
INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'HIP HOP');
INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'RAP');

CREATE TABLE TOPAZ.TB_COMPACT_DISC 
(
	TB_FAIXA_ID				UNIQUEIDENTIFIER NOT NULL,
	TB_GENERO_ID			UNIQUEIDENTIFIER NOT NULL,
	TITULO					NVARCHAR(50) NOT NULL,
	DATA_CADASTRO			DATETIME NOT NULL DEFAULT GETDATE(),
	PRIMARY KEY(TB_FAIXA_ID),
	INDEX TB_COMPACT_DISC_FKIndex2(TB_FAIXA_ID),
	INDEX TB_COMPACT_DISC_FKIndex3(TB_GENERO_ID),
	FOREIGN KEY(TB_FAIXA_ID)
	REFERENCES TOPAZ.TB_FAIXA(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	FOREIGN KEY(TB_GENERO_ID)
	REFERENCES TOPAZ.TB_GENERO(ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
);

